version: '3.1'
volumes:
    node_modules:

services:

  db:
    image: mysql:8
    restart: always
    env_file: ./var.env

  nodejs:
    build:
      context: ../
      dockerfile: ./env/Dockerfile
    image: mountain_climb/nodejs:1.0.0
    restart: always
    ports:
      - 8080:8080
    volumes:
        - ../:/app
        - node_modules:/app/node_modules
    container_name: nodejs
    command: ["pm2-runtime", "start", "./ecosystem.config.js", "--env", "develop"]
