// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FLUTTER_APIKEY'),
    appId: '1:139433871572:web:716b01764abafab78e9341',
    messagingSenderId: '139433871572',
    projectId: 'wa-project-mountain',
    authDomain: 'wa-project-mountain.firebaseapp.com',
    storageBucket: 'wa-project-mountain.appspot.com',
    measurementId: 'G-9WDVTNCPF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FLUTTER_APIKEY_ANDROID'),
    appId: '1:139433871572:android:acf8cd2e94eb074f8e9341',
    messagingSenderId: '139433871572',
    projectId: 'wa-project-mountain',
    storageBucket: 'wa-project-mountain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FLUTTER_APIKEY_IOS'),
    appId: '1:139433871572:ios:13d655e3cd7c37d08e9341',
    messagingSenderId: '139433871572',
    projectId: 'wa-project-mountain',
    storageBucket: 'wa-project-mountain.appspot.com',
    iosClientId:
        '139433871572-gev37mhgvmqdbibl8jknki4l3tjjr974.apps.googleusercontent.com',
    iosBundleId: 'com.waproject.mountain.dev',
  );
}
