name: Deploy Flutter Web

on:
  push:
    branches:
      - 'fix-func'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.0.0'

      - name: Install Dependencies
        working-directory: './frontend'
        run: |
          flutter upgrade && \
          flutter pub get

      - name: Build the application
        working-directory: './frontend'
        env:
          FLUTTER_APIKEY: ${{ secrets.FLUTTER_APIKEY }}
        run: flutter build web --dart-define FLUTTER_APIKEY=$FLUTTER_APIKEY --release --web-renderer html

      - name: Store static file
        uses: actions/upload-artifact@master
        with:
          name: build-flutter
          path: frontend/build/web

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: 'build'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: build-flutter
          path: frontend/build/web

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
