name: Build, Release app to Github Pages and Firebase Hosting

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: 'Run flutter pub get'
        working-directory: frontend
        run: flutter pub get

      - name: Enable flutter web
        working-directory: frontend
        run: flutter config --enable-web

      - name: build
        working-directory: frontend
        run: flutter build web
        with:
          name: build
          path: build/web

      - uses: peaceiris/actions-gh-pages@v3

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
