name: Analyze, Build and Deploy

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.0.0'
      - name: Install Dependencies
        working-directory: './frontend'
        run: |
          flutter upgrade && \
          flutter pub get
      - name: Build the application
        working-directory: './frontend'
        run: flutter build web
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build/web

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 📚 Checkout repo
        uses: actions/checkout@v3
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
